#!/bin/bash
# fix-dual-nic-arp.sh — Fix ARP when two NICs share the same subnet.
#
# Only applies the fix if eth0 and eth1 are on the same subnet.
# Runs as a oneshot service on first disk boot.
#
# Problem: Linux's weak host model sends ARP replies out the wrong interface,
#          making eth0 unreachable via unicast.
# Solution: arp_filter + arp_announce sysctls + source-based policy routing.

set -euo pipefail

LOG="/var/log/fix-dual-nic-arp.log"
exec > >(tee -a "$LOG") 2>&1

echo "[$(date)] Checking if dual NIC ARP fix is needed..."

# Get IPs and subnets for eth0 and eth1
ETH0_CIDR=$(ip -4 -o addr show eth0 2>/dev/null | awk '{print $4}' | head -1)
ETH1_CIDR=$(ip -4 -o addr show eth1 2>/dev/null | awk '{print $4}' | head -1)

if [ -z "$ETH0_CIDR" ] || [ -z "$ETH1_CIDR" ]; then
    echo "[SKIP] eth0 or eth1 has no IP — single NIC or not configured"
    exit 0
fi

# Compute network address for each interface
net_addr() {
    local ip="${1%/*}" mask="${1#*/}"
    IFS='.' read -r a b c d <<< "$ip"
    local full_mask=$((0xFFFFFFFF << (32 - mask) & 0xFFFFFFFF))
    local ma=$(( (full_mask >> 24) & 0xFF ))
    local mb=$(( (full_mask >> 16) & 0xFF ))
    local mc=$(( (full_mask >> 8) & 0xFF ))
    local md=$(( full_mask & 0xFF ))
    echo "$((a & ma)).$((b & mb)).$((c & mc)).$((d & md))/$mask"
}

ETH0_NET=$(net_addr "$ETH0_CIDR")
ETH1_NET=$(net_addr "$ETH1_CIDR")

echo "  eth0: $ETH0_CIDR (network: $ETH0_NET)"
echo "  eth1: $ETH1_CIDR (network: $ETH1_NET)"

if [ "$ETH0_NET" != "$ETH1_NET" ]; then
    echo "[SKIP] Different subnets — no fix needed"
    exit 0
fi

echo "[APPLY] Same subnet detected — applying ARP fix..."

ETH0_IP="${ETH0_CIDR%/*}"
SUBNET="${ETH0_NET}"
GW=$(ip route show default dev eth1 2>/dev/null | awk '{print $3}' | head -1)
GW="${GW:-$(ip route show default 2>/dev/null | awk '{print $3}' | head -1)}"
TABLE=100

# 1. Strict ARP
sysctl -w net.ipv4.conf.all.arp_filter=1
sysctl -w net.ipv4.conf.all.arp_announce=2
cat > /etc/sysctl.d/99-arp-fix.conf << EOF
net.ipv4.conf.all.arp_filter=1
net.ipv4.conf.all.arp_announce=2
EOF

# 2. Source-based routing
ip rule add from "$ETH0_IP" table "$TABLE" 2>/dev/null || true
ip route replace ${SUBNET} dev eth0 src "$ETH0_IP" table "$TABLE"
if [ -n "$GW" ]; then
    ip route replace default via "$GW" dev eth0 table "$TABLE"
fi

# 3. Persist in interface config
IFCFG="/etc/network/interfaces.d/ifcfg-eth0"
if [ -f "$IFCFG" ] && ! grep -q "table $TABLE" "$IFCFG"; then
    sed -i "/^# END AUTOGENERATED/i \\
\tpost-up ip rule add from $ETH0_IP table $TABLE 2>/dev/null || true\\
\tpost-up ip route add ${SUBNET} dev eth0 src $ETH0_IP table $TABLE 2>/dev/null || true\\
\tpost-up ip route add default via ${GW} dev eth0 table $TABLE 2>/dev/null || true" "$IFCFG"
fi

echo "[OK] ARP fix applied for eth0 ($ETH0_IP) — table $TABLE, gateway $GW"
