---
all:
  children:
    hypervisor:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    proxmox:
      hosts:
        proxmox-ve:
          ansible_host: "{{ proxmox_api_host }}"
          ansible_user: "{{ proxmox_ssh_user | default('root') }}"
          ansible_password: "{{ proxmox_ssh_password | default(proxmox_api_password) }}"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
