---
# Run 18-point validation on Kairos compute node.
- name: Validate Kairos deployment
  hosts: localhost
  gather_facts: true
  pre_tasks:
    - name: Load deployment facts
      ansible.builtin.include_tasks: load-deploy-facts.yml
  roles:
    - validate
